Pin slack client, breaking change
apache/superset pull request #10345
Opened 2020-07-16 16:41 UTC by bkyryliuk

Slack client versions > 2.5.0 do not accept the file content anymore. It broke the slack integration.
Added test that would capture undesired upgrades.
Eventually we can fix via writing a tmp file and then uploading it.

### TEST PLAN
* ipython
* unit test
* dropbox staging

2020-07-16 20:21 UTC, villebro commented
@bkyryliuk do I understand correctly that the new version doesn't support file-like objects, but requires files to be persisted to disk prior to submission?

2020-07-16 21:32 UTC, bkyryliuk commented
> @bkyryliuk do I understand correctly that the new version doesn't support file-like objects, but requires files to be persisted to disk prior to submission?

yes
I did not dig much into the changes in the lib. We have been using 2.5.0 for last 3 month at dropbox.
I used this snippet in ipython to find the version that had the regression
```
import logging
logging.basicConfig(level=logging.DEBUG)

import os
from slack import WebClient
from slack.errors import SlackApiError
slack_token='your_token'
client = WebClient(token=slack_token)
fn = '/Users/bogdankyryliuk/Desktop/Screen Shot 2020-07-16 at 9.03.49 AM.png'
in_file = open(fn, "rb")
data = in_file.read()
response = client.files_upload(
  channels="#bogdan-test2",
  file=data,
  title="Test upload"
)
```

2020-07-17 05:18 UTC, mistercrunch commented
Had the issue been reported on their GitHub? If so can we link to it? If not can we report it?

2020-07-17 06:52 UTC, villebro commented
https://github.com/slackapi/python-slackclient/issues/728

Seems like making it a file-like object (`io.BytesIO`) instead of `bytearray` fixes it in `>2.5.0, <2.7.2`. Since `2.7.2` is already out, we should probably bump to that version?

2020-07-18 08:12 UTC, villebro requested changes
Check my comment above. I propose bumping to `2.7.2`.

2020-07-20 16:15 UTC, bkyryliuk commented
> [slackapi/python-slackclient#728](https://github.com/slackapi/python-slackclient/issues/728)
> 
> Seems like making it a file-like object (`io.BytesIO`) instead of `bytearray` fixes it in `>2.5.0, <2.7.2`. Since `2.7.2` is already out, we should probably bump to that version?

This seems to work:
```
 response = client.files_upload(channels="#bogdan-test2", file=io.BytesIO(b'blabla'), title="Test upload", filename="test.png")
```

I am on PTO today, won't be able to test this approach on our staging. 
My suggestion here would be to merge the library downgrade and I can do a fix forward a bit later this week.

2020-07-20 16:19 UTC, villebro approved these changes
To get this unblocked for `0.37`, in discussions with @bkyryliuk  we decided to get this merged and follow up with a `2.7.2` bump later after it has been properly tested at Dropbox.

2020-07-20 16:20 UTC, merged