Replace reactable with DataTable from superset-ui in ChangeDatasourceModal
apache/superset pull request #10982
Opened 2020-09-21 19:37 UTC by kgabryje

### SUMMARY
The goal is to replace all uses of `reactable-arc` library with DataTable from superset-ui (which uses `react-table` under the hood) and keep the UI/UX mostly unchanged. The reason for that is that `reactable-arc` has been unsupported for 2 years now, uses deprecated lifecycle methods and is incompatible with Typescript.
This PR replaces `reactable-arc` in `ChangeDatasourceModal` component.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:

![image](https://user-images.githubusercontent.com/15073128/93812891-85c4b380-fc52-11ea-908d-045eb62a7d52.png)

After:

![image](https://user-images.githubusercontent.com/15073128/93812727-4f873400-fc52-11ea-9ddf-466907694bb1.png)

### TEST PLAN

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2020-09-21 19:37 UTC, kgabryje commented
@rusackas Can you take a look please?

2020-09-21 22:23 UTC, rusackas commented
Is it possible to get rid of the blank row and extra horizontal gray line at the top of the list?

![Pasted_Image_9_21_20__3_22_PM](https://user-images.githubusercontent.com/812905/93827525-47150600-fc1e-11ea-95ed-13e36dfb517f.png)

2020-09-21 22:25 UTC, rusackas commented
![Pasted_Image_9_21_20__3_22_PM](https://user-images.githubusercontent.com/812905/93827723-b854b900-fc1e-11ea-8c71-824344b0a773.png)

This cropped text is a little worrisome, too... when it's visible, it indicates that there's something to scroll (that's a good thing) but looks a little weird. I _assume_ that depending on the size of your window, you may not see that partial line, and therefore might have no idea that you should scroll.

So, could we maybe...
1) Make the modal fit the whole content area?
2) Show a scrollbar if it _can't_ fit?
![Pasted_Image_9_21_20__3_22_PM](https://user-images.githubusercontent.com/812905/93827599-69a71f00-fc1e-11ea-9ddc-c25c41871b23.png)

2020-09-22 06:34 UTC, kgabryje commented
> Is it possible to get rid of the blank row and extra horizontal gray line at the top of the list?
> 
> ![Pasted_Image_9_21_20__3_22_PM](https://user-images.githubusercontent.com/812905/93827525-47150600-fc1e-11ea-95ed-13e36dfb517f.png)

That is a strange behaviour of DataTable with `sticky` param - for some reason it wraps `<thead>` and `<tbody>` in separate `<table>` tags, and table has margin bottom set. That happens in `StickyWrap` component in `superset-ui/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx` file. I'll try to figure out how to prevent it.

2020-09-22 08:47 UTC, kgabryje commented
@rusackas I did some css tweaks. They're not pretty but were necessary to override some DataTable styles

2020-09-23 04:17 UTC, rusackas commented
> That is a strange behaviour of DataTable with `sticky` param - for some reason it wraps `<thead>` and `<tbody>` in separate `<table>` tags, and table has margin bottom set. That happens in `StickyWrap` component in `superset-ui/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx` file. I'll try to figure out how to prevent it.

Hmm... maybe a `styled` wrapper could be used to remove the padding/margin and excess border/line. Let me know if you'd like to (or would like me to) take a look at that in a separate PR, or spend a little more time on it with this one. I think the modal hight and/or making the scrolling more noticeable is probably more important anyway.

2020-09-23 04:36 UTC, ktmud commented
You can wrap the `DataTable` in a styled div like the `TableChart` does: https://github.com/apache-superset/superset-ui/blob/516b4d57b88bbadfbabebdb84b4862ce210bd350/plugins/plugin-chart-table/src/TableChart.tsx#L285

Here is the CSS: https://github.com/apache-superset/superset-ui/blob/516b4d57b88bbadfbabebdb84b4862ce210bd350/plugins/plugin-chart-table/src/Styles.tsx#L3

`DataTable` is designed to be CSS-less so it is library-agnostic.

Separate tables are needed to sticky headers because the scrollable container must contain only the table body (otherwise we could just use `position: sticky` on the `th` cells)---which was the original behavior of `jquery.DataTables` this component was created to replace..

2020-09-23 15:24 UTC, kgabryje commented
@rusackas @ktmud Thank you for your suggestions. Before you suggested using `styled` and styles from superset-ui, I wrote some css of my own that removed the excessive margin and added permanent scrollbar. Do you think I should refactor or can we go with what we currently have?

2020-09-28 22:58 UTC, rusackas commented
> @rusackas @ktmud Thank you for your suggestions. Before you suggested using `styled` and styles from superset-ui, I wrote some css of my own that removed the excessive margin and added permanent scrollbar. Do you think I should refactor or can we go with what we currently have?

I would prefer the refactor if it's possible, for a few reasons:
1) We're trying to make the LESS codebase smaller, rather than add anything more to it (we'd like to one day remove these global file styles, if it becomes possible).
2) Add the styles within the components that they concern, so that future people can refactor/add/remove styles more easily (i.e. within the components, thus the shift to Emotion)
3) You could use Theme variables... in the CSS on this PR, for example, you could use the 4px `gridUnit`(or multiples of it) used in an increasing number of places in superset. The idea here is that no fonts/sizes/colors should be hard-coded in an effort to eventually make Superset more themeable.

2020-09-28 23:00 UTC, rusackas commented on superset-frontend/stylesheets/superset.less
> +.flex-1 {
Is there a reason not to have this just be part of the .sticky-table class?

2020-10-01 04:30 UTC, rusackas requested changes
Hoping it's an easy change, but would love to see the styles added within components themselves with Emotion rather than adding to the LESS codebase (which we hope to make smaller, rather than bigger). It also allows us to use Theme variables, which I'll add some suggestions for on the relevant lines.

2020-10-01 04:36 UTC, rusackas commented on superset-frontend/stylesheets/superset.less
> +          -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, 0.5);
```suggestion
          -webkit-box-shadow: 0 0 1px ${({ theme }) => theme.colors.secondary.light5}80;
```
This should look the same, but be more theming friendly _(helooooo dark mode!)_

2020-10-01 04:37 UTC, rusackas commented on superset-frontend/stylesheets/superset.less
> +          background-color: rgba(0, 0, 0, 0.5);
```suggestion
          background-color: ${({ theme }) => theme.colors.secondary.dark2}80;
```
Should be more themable this way

2020-10-01 04:38 UTC, rusackas commented on superset-frontend/stylesheets/superset.less
> +          border-radius: 4px;
if these are in emotion, this can be:
`bborder-radius: ${({ theme }) => theme.gridUnit}px;`

2020-10-01 04:41 UTC, rusackas commented on superset-frontend/stylesheets/superset.less
> +            width: 7px;
Not sure if this 7px measurement (and the one below it) need to be exactly 7px, but if it's just _about that big_ then if this were moved to Emotion I would do `width: ${({ theme }) => theme.gridUnit * 2}px` to make it themable
```
            width: 7px;
```

2020-10-01 20:04 UTC, kgabryje commented
@rusackas I moved the styles to a styled component and used variables from theme. Can you take a look?

2020-10-03 23:35 UTC, rusackas approved these changes
LGTM!

2020-10-03 23:42 UTC, rusackas commented on superset-frontend/src/datasource/ChangeDatasourceModal.tsx
> +import DataTable from '@superset-ui/plugin-chart-table/lib/DataTable';
@kgabryje @ktmud Just a note that this is the second time this table has been imported/used. Anyone think it seems a little weird? I'm all for reusing code! Maybe it should be moved out of the table plugin and into a @superset-ui/core export, if this is going to happen more frequently. ¯\\\_(ツ)_/¯

2020-10-05 12:07 UTC, kgabryje commented
@rusackas Due to [this](https://github.com/apache/incubator-superset/issues/11142) issue, which is related to changes made here, what do you think about postponing merging this PR until the issue is resolved? So that we don't risk another regression.

2020-10-12 15:37 UTC, closed without merging

2020-10-20 06:13 UTC, ktmud commented on superset-frontend/src/datasource/ChangeDatasourceModal.tsx
> +import DataTable from '@superset-ui/plugin-chart-table/lib/DataTable';
Yes, there was a plan to move it out. I never followed up with it because of priorities. Will try to get it done by the end of this year!