fix: uneven list header padding (#12029)
apache/superset pull request #12412
Opened 2021-01-11 17:25 UTC by michael-s-molina

### SUMMARY
Adjust list header padding.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
<img width="1118" alt="Screen Shot 2021-01-11 at 11 58 16 AM" src="https://user-images.githubusercontent.com/70410625/104216234-8ad38b80-5418-11eb-9ca7-65cd87024a36.png">
<img width="1113" alt="Screen Shot 2021-01-11 at 2 21 52 PM" src="https://user-images.githubusercontent.com/70410625/104216252-91620300-5418-11eb-98d2-0b867205a049.png">

Closes #12029 

@junlincc 

### TEST PLAN
1 - Go to any major list (charts, dashboards, databases, etc)
2 - Check header padding

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-01-11 18:50 UTC, geido requested changes

2021-01-11 18:50 UTC, geido commented on superset-frontend/src/components/dataViewCommon/TableCollection.tsx
> +      min-height: ${({ theme }) => theme.gridUnit * 6}px;
line-height might be more appropriate here

2021-01-11 18:50 UTC, geido commented on superset-frontend/src/components/dataViewCommon/TableCollection.tsx
> +    height: ${({ theme }) => theme.gridUnit * 11}px;
This should be unnecessary

2021-01-11 22:02 UTC, adam-stasiak commented
tested - No issues found

2021-01-12 15:14 UTC, geido approved these changes

2021-01-12 18:55 UTC, junlincc approved these changes
LGTM, perfect!
After:
<img width="1095" alt="Screen Shot 2021-01-12 at 10 49 38 AM" src="https://user-images.githubusercontent.com/67837651/104359245-46052e80-54c4-11eb-8cfb-bf32ab1cc4ad.png">

Before:
<img width="958" alt="Screen Shot 2021-01-12 at 10 50 14 AM" src="https://user-images.githubusercontent.com/67837651/104359289-51f0f080-54c4-11eb-95d4-b64e3c356c80.png">

@nytai please take a look since we touched your area. 

NOTE⚠️: 
- This is only Product and QA approval with NO code reviews 
- This approval indicates that all UI changes meet product requirement, no noticeable regression is   introduced
- This approval indicates this PR is ready for code reviews

2021-01-13 07:22 UTC, rusackas approved these changes

2021-01-13 07:24 UTC, rusackas commented
Code looks good to me. Tempted to do the usual nag about `gridUnit`, but I don't like fractional `gridUnit`s, so I'll let the `2px` go :)

I'd merge this, but would love to have @nytai's nod of approval first :D

2021-01-13 07:26 UTC, nytai approved these changes

2021-01-13 07:29 UTC, merged