refactor: Bootstrap to AntD - Label
apache/superset pull request #12774
Opened 2021-01-26 17:47 UTC by michael-s-molina

### SUMMARY
- Migrates Label component from Bootstrap to AntD.
- Removes unused properties.
- Add typescript checking to `bsStyle` property.
- Improves CSS readability.
- Modifies storybook to use controls instead of handles.
- Updates tests.

See: #10254

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
<img width="575" alt="Screen Shot 2021-01-26 at 2 09 26 PM" src="https://user-images.githubusercontent.com/70410625/105881857-c7d87a00-5fe3-11eb-9b11-bcf012941ae8.png">
<img width="539" alt="Screen Shot 2021-01-26 at 2 28 45 PM" src="https://user-images.githubusercontent.com/70410625/105881877-cdce5b00-5fe3-11eb-8ffb-1adb320a3ce9.png">
<img width="308" alt="Screen Shot 2021-01-26 at 2 10 08 PM" src="https://user-images.githubusercontent.com/70410625/105881861-c9a23d80-5fe3-11eb-82ee-d4cf272eb3aa.png">
<img width="306" alt="Screen Shot 2021-01-26 at 2 27 07 PM" src="https://user-images.githubusercontent.com/70410625/105881872-cd35c480-5fe3-11eb-86fa-13d6013508be.png">
<img width="886" alt="Screen Shot 2021-01-26 at 2 27 29 PM" src="https://user-images.githubusercontent.com/70410625/105881875-cd35c480-5fe3-11eb-9b29-22687e5c44e1.png">
<img width="883" alt="Screen Shot 2021-01-26 at 2 12 56 PM" src="https://user-images.githubusercontent.com/70410625/105881866-cb6c0100-5fe3-11eb-8c24-3decfe14468b.png">
<img width="1157" alt="Screen Shot 2021-01-26 at 2 10 59 PM" src="https://user-images.githubusercontent.com/70410625/105881863-ca3ad400-5fe3-11eb-8d62-efd9fc471f80.png">
<img width="1153" alt="Screen Shot 2021-01-26 at 2 26 49 PM" src="https://user-images.githubusercontent.com/70410625/105881869-cc049780-5fe3-11eb-9034-cefa67895815.png">

@rusackas @junlincc

### TEST PLAN
1 - Open any screen that contains a label (explore, profile, dashboards, etc.)
2 - All labels should have the same theme and behavior
3 - Additional testing can be done using Storybook

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-01-27 07:40 UTC, rusackas commented on superset-frontend/src/components/Label/Label.test.tsx
> -  it('renders all the sorybook gallery variants', () => {
oops!

2021-01-27 07:44 UTC, rusackas commented on superset-frontend/src/components/Label/index.tsx
> +export type BsStyle =
The name BsStyle/bsStyle is a reference to bootstrap. Now that it's out of the picture, we can rename this globaly to something more general, like type/variant/style/etc.

2021-01-27 07:55 UTC, rusackas commented on superset-frontend/src/components/Label/index.tsx
> +      baseColor = primary;
This is all so much cleaner. Love it!

2021-01-27 07:56 UTC, rusackas requested changes
This is looking fantastic! Ready to approve, but would like to change that bsStyle prop name.

2021-01-27 16:57 UTC, adam-stasiak commented
I can see that Database label is a little bit moved. On master is straight.
<img width="1424" alt="Zrzut ekranu 2021-01-27 o 17 12 48" src="https://user-images.githubusercontent.com/25153919/106024931-8a015180-60c8-11eb-9253-044c7179e83c.png">

2021-01-27 17:05 UTC, michael-s-molina commented
> I can see that Database label is a little bit moved. On master is straight.
> <img alt="Zrzut ekranu 2021-01-27 o 17 12 48" width="1424" src="https://user-images.githubusercontent.com/25153919/106024931-8a015180-60c8-11eb-9253-044c7179e83c.png">
> No other info found. @junlincc Could you set priority on this?

@adam-stasiak Thank you so much for reviewing! I'll wait until the end of today to see if you find anything else so I can commit the fixes only once.

2021-01-27 19:16 UTC, michael-s-molina commented
@adam-stasiak Thank you so much for reviewing! Fixed!

2021-02-02 06:15 UTC, rusackas approved these changes
LGTM!

2021-02-02 06:15 UTC, merged