feat: error messages when connecting to mssql
apache/superset pull request #14171
Opened 2021-04-15 16:31 UTC by AAfghahi

### SUMMARY
Added custom error messages for an incorrect database name, cleaned up some language in other tests. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
![Screen Shot 2021-04-15 at 12 14 47 PM](https://user-images.githubusercontent.com/48933336/114904996-7374b780-9de6-11eb-83d3-74c16f9917c1.png)
### TEST PLAN
added unit tests

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-04-15 21:48 UTC, betodealmeida commented on superset/errors.py
> +                "Issue 1015 - The database is " "spelled incorrectly or does not exist."
```suggestion
                "Issue 1015 - The database is spelled incorrectly or does not exist."
```

2021-04-15 21:52 UTC, betodealmeida requested changes
The copy in issue 1015 should be identical everywhere.

2021-04-15 22:05 UTC, AAfghahi commented
sounds good, will update and then ping you.

2021-04-16 16:43 UTC, betodealmeida approved these changes
Awesome sauce!

2021-04-16 16:43 UTC, merged