Work in progress. Support week_ending_saturday for Druid.
apache/superset pull request #1491
Opened 2016-10-31 16:52 UTC by bkyryliuk

2016-11-01 00:16 UTC, bkyryliuk commented on caravel/models.py
> +                '5 minutes', '1 hour', '6 hour', '1 day', '7 days',
@mistercrunch - are we using those ?

2016-11-02 00:49 UTC, mistercrunch requested changes

2016-11-02 00:49 UTC, mistercrunch commented on caravel/models.py
> +        granularity = {'type': 'period', 'period': iso_8601_dict[period_name]}
I think granularity is a free form select, which means you should use something like `iso_8601_dict.get(iso_8601_dict)` and fallback on passing in as `duration` if the entry is not in the dict

2016-11-02 00:49 UTC, mistercrunch commented on caravel/models.py
> +            for i in range(len(df['timestamp'])):
oh with pandas dataframe you always want to do set operations, something like `df.timestamp += timedelta(days=1)` should work. If you're doing it right, there's almost never a need to write a loop.

2016-11-02 20:19 UTC, mistercrunch approved these changes

2016-11-02 20:20 UTC, mistercrunch commented
LGTM, though please think the implications of the timezone related changes. Could that change existing charts in ways that users may not expect or desire?

2016-11-03 01:45 UTC, merged