refactor: icon to icons for sqllab
apache/superset pull request #15593
Opened 2021-07-08 18:22 UTC by pkdotson

### SUMMARY
This pr migrates the icons in sqllab editor to the new icons component.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before
<img width="466" alt="Screen Shot 2021-07-08 at 6 29 50 AM" src="https://user-images.githubusercontent.com/17326228/124971897-9aeeb100-dfde-11eb-9a21-bd7b8f4509ad.png">
<img width="131" alt="1 SAVE AS" src="https://user-images.githubusercontent.com/17326228/124971990-ae018100-dfde-11eb-8a7d-83d90b6a5a1f.png">
<img width="128" alt="COPY LINK" src="https://user-images.githubusercontent.com/17326228/124972028-bbb70680-dfde-11eb-9646-19644ec094ab.png">

after
<img width="375" alt="Screen Shot 2021-07-08 at 7 16 05 AM" src="https://user-images.githubusercontent.com/17326228/124971927-a0e49200-dfde-11eb-8985-1db477d7a4e2.png">
 <img width="118" alt="SAVE AS" src="https://user-images.githubusercontent.com/17326228/124972007-b3f76200-dfde-11eb-975c-ccf25450fb9a.png">
<img width="123" alt="2 COPY LINK" src="https://user-images.githubusercontent.com/17326228/124972051-c2de1480-dfde-11eb-8bdd-41846d295169.png">

### TESTING INSTRUCTIONS
Go to sql editor to check out icons

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-07-09 22:54 UTC, suddjian commented on superset-frontend/src/SqlLab/components/ShareSqlLabQuery.tsx
> +const SytledIcon = styled(Icons.Link)`
typo: StyledIcon

2021-07-09 22:55 UTC, suddjian commented on superset-frontend/src/SqlLab/components/ShareSqlLabQuery.tsx
> +        <SytledIcon
```suggestion
        <StyledIcon
```

2021-07-09 22:55 UTC, suddjian approved these changes

2021-07-09 22:55 UTC, suddjian commented
Approved with typo corrections

2021-07-10 12:17 UTC, michael-s-molina requested changes

2021-07-10 12:17 UTC, michael-s-molina commented on superset-frontend/src/SqlLab/components/ShareSqlLabQuery.tsx
>            color={
```suggestion
          iconColor={
```

2021-07-12 15:31 UTC, fintzd approved these changes
I guess it's all good, suggested changes were added

2021-07-12 16:40 UTC, michael-s-molina approved these changes

2021-07-12 17:24 UTC, merged