add timezone to report schedule
apache/superset pull request #15747
Opened 2021-07-16 18:54 UTC by eschutho

### SUMMARY
Adds timezone to report schedule db in order to allow us to add a UI on the reports for users to select a timezone for their schedule. Timezones are strings of locations, such as "America/Los_Angeles" or "UTC".

The default value of UTC as an example will be GMT, which is the current +0 offset time that we are using. 

In the future UI, the plan is to "guess" the user's timezone and default the selection to their current timezone. 

![TimezoneSelector_-_Interactive_Timezone_Selector_⋅_Storybook](https://user-images.githubusercontent.com/5186919/125994241-19404025-40bb-4668-a2fb-d37de7a10a0f.png)

For context, the full PR is https://github.com/apache/superset/pull/15743/files

### TESTING INSTRUCTIONS
results of db migration script:

Current: 0.33 s
10+: 0.34 s
100+: 0.32 s
1000+: 0.33 s

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [x] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-07-19 16:39 UTC, betodealmeida requested changes

2021-07-19 16:39 UTC, betodealmeida commented on superset/migrations/versions/ae1ed299413b_add_timezone_to_report_schedule.py
> +    )
Older versions of SQLite do not support adding/dropping columns, so we use batch mode in cases like this (https://alembic.sqlalchemy.org/en/latest/batch.html).

```suggestion
    with op.batch_alter_table("report_schedule") as batch_op:
        batch_op.add_column(
            sa.Column(
                "timezone", sa.String(length=100), nullable=False, server_default="UTC"
            ),
        )
```

2021-07-19 16:39 UTC, betodealmeida commented on superset/migrations/versions/ae1ed299413b_add_timezone_to_report_schedule.py
> +    op.drop_column("report_schedule", "timezone")
Same here:

```suggestion
     with op.batch_alter_table("report_schedule") as batch_op:
        batch_op.drop_column("timezone")
```

2021-07-19 17:34 UTC, eschutho commented
thanks @betodealmeida

2021-07-19 18:54 UTC, eschutho commented
The failing test is at `ERROR at setup of TestImportExport.test_import_2_slices_for_same_table ____`

2021-07-22 22:15 UTC, betodealmeida approved these changes

2021-07-22 22:36 UTC, merged