update tables unique key
apache/superset pull request #15833
Opened 2021-07-22 08:43 UTC by FishermanZzhang

### SUMMARY

update dataset(tables) unique key

i just test on mysql. and I know the sqlite no support. 

https://github.com/apache/superset/pull/14393

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [x] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-07-23 04:40 UTC, john-bodley commented
@FishermanZzhang this wont work as every database encodes uniqueness with `NULL` differently.

2021-07-23 10:19 UTC, FishermanZzhang commented
> @FishermanZzhang, sadly this wont work as every database encodes uniqueness with `NULL` differently.

 In my opinion. `SQLALCHEMY_DATABASE_URI = 'mysql://{user}:{passwd}@{host}/superset` is best.

2021-10-25 14:33 UTC, craig-rueda requested changes

2021-11-24 15:04 UTC, betodealmeida requested changes
Can you give context on why we'd want to add this constraint?

Also, this model is going away soon, see SIP-68 (https://github.com/apache/superset/issues/14909). The new model separates tables (which will have a uniqueness constraint) from datasets (which can point to the same table).

2021-11-24 15:05 UTC, betodealmeida commented
Closing this, since https://github.com/apache/superset/issues/14909 will replace it.

2021-11-24 15:05 UTC, closed without merging