fix: Safari is not showing scroll bars in Explore
apache/superset pull request #16089
Opened 2021-08-05 13:05 UTC by michael-s-molina

### SUMMARY
Fix https://github.com/apache/superset/issues/16072

@junlincc @jinghua-qa @rusackas 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/128354308-b59a6557-f8bd-4bab-8e1b-70167adc626b.mov

https://user-images.githubusercontent.com/70410625/128354409-dda33190-f0f0-4356-b262-96782e20452d.mov

### TESTING INSTRUCTIONS
See the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-08-05 13:07 UTC, michael-s-molina commented on superset-frontend/src/explore/components/ExploreViewContainer.jsx
> +            height: 100%;
The `#app` should account for `#app-menu` height. That's why I change it to percentage and set the `body` to `100vh`.

2021-08-05 15:25 UTC, kgabryje commented
/testenv up

2021-08-05 18:31 UTC, junlincc commented
/testenv up

2021-08-05 19:19 UTC, junlincc commented
thank you so much for the quick fix! 
https://user-images.githubusercontent.com/67837651/128408432-6f035ca2-de27-4d85-96f5-efabb4311fa8.mov

looks like the top padding is missing?

2021-08-05 20:35 UTC, junlincc requested changes, later dismissed
padding above run buttons is missing 😅

2021-08-05 21:02 UTC, michael-s-molina commented
@junlincc I wasn't able to reproduce this behavior in the test env. Tested in Safari and Chrome. 🤔 

https://user-images.githubusercontent.com/70410625/128420570-1a9d165a-49ed-455b-a5f2-7e12f94c8fd2.mov

2021-08-06 16:22 UTC, kgabryje commented
@junlincc I'm not able to reproduce as well

2021-08-09 23:50 UTC, rusackas approved these changes
LGTM!

2021-08-10 10:51 UTC, michael-s-molina commented
@junlincc Can you unblock?

2021-08-10 13:41 UTC, merged

2021-08-10 22:05 UTC, rosemarie-chiu commented
🏷 2021.31