[WIP] fix(import-dashboards): Match db via name not UUID
apache/superset pull request #16606
Opened 2021-09-06 09:58 UTC by EBoisseauSierra

### SUMMARY

NB: We're here discussing the `import-dashboards` CLI with the `VERSIONED_EXPORT` feature flag *turned ON* — cf. #11349

Currently, `superset import-dashboards` looks up at the required databases (`export/databases/*.yaml`). If the db URI (`sqlalchemy_uri` key) contains a masked password, then the script looks up for already existing databases record.

The match is currently done using db UUID. However, '<insert how UUIDs are generated>', the same db connection (same URI) might not have the same UUID on the export instance, and on the import one. (Cf. #16395)

Thus, we propose to lookup for the db _name_ instead — this would also allow for updating the db URI between the export and the import instance.

### TESTING INSTRUCTIONS

WIP — help required

### ADDITIONAL INFORMATION

- [x] Has associated issue: #16395 
- [x] Required feature flags: `"VERSIONED_EXPORT": True`
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-10-07 15:29 UTC, betodealmeida commented
Let me take a look at the original problem again. I'm worried about this PR because the assumption that we match on UUID is baked on a lot of the design decisions.

2021-10-07 15:55 UTC, betodealmeida requested changes
Let's consider other alternatives first.

2021-10-07 21:12 UTC, EBoisseauSierra commented
@krsnik93 you're right: this PR aimed to fix an issue we had where using _the same_ URI on two different machine yield to two different UUID (I haven't investigated where they are generated) — so the matching at import is failing (the pw in the archive is masked, and even if the URI/db connection already exist in Superset thanks to the set-database-uri, it is not reconciled because of the different UUIDs).

But this issue of non-deterministic/reproducible UUIDs (and thus, failing import) — that my PR tries to solve by using the db connection name as lookup key — is, IMHO, a subset of a more generic problem that is “how to import-dashboards, but update the db URI on the fly?” (or use the previously instantiated db connection, using db connection name as lookup key).

2021-10-13 08:37 UTC, PowerPlop commented
@EBoisseauSierra  when I import a dashboard via the UI (or API), it does not seem to validate if the database connection is valid?

Our process is:

1. Develop dashboard in dev/locally
2. Export to zip
3. Commit unzipped
4. import dashboard in PRD (zipped) via API
5. update database connection url (manually or scripted / first time only)

When updating an existing dashboard we simply import them again with option 'Overwrite' for dashboard,chart and dataset. The database record is not changed (only at initial import).

2022-04-27 19:46 UTC, closed without merging