Add 'Save As' feature for dashboards
apache/superset pull request #1669
Opened 2016-11-23 00:47 UTC by the-dcruz

## Overview
Allow user to edit an existing dashboard, and then save it as their own.

## Screenshots
### Overwrite dashboard
![dash_save_as_1](https://cloud.githubusercontent.com/assets/1399237/20547742/1ed09bd6-b0d3-11e6-8199-9c1937c6c393.gif)

### Copy dashboard
![dash_save_as_2](https://cloud.githubusercontent.com/assets/1399237/20547749/2ae801ca-b0d3-11e6-9de4-de1d2b654f88.gif)

2016-11-23 00:47 UTC, the-dcruz commented
@mistercrunch @ascott

2016-11-23 01:41 UTC, mistercrunch requested changes
Amazing, thanks for this very neat PR adding a key feature! I had a few nits but overall it looks great.

2016-11-23 01:41 UTC, mistercrunch commented on superset/assets/javascripts/dashboard/components/SaveModal.jsx
> +              name="newDashName"
it'd be a nice touch if `onFocus` it would select the `radio.newDashboard` option above

2016-11-23 01:41 UTC, mistercrunch commented on superset/assets/javascripts/dashboard/components/SaveModal.jsx
> +            {' Save as: '}
oh, is that a nicer way to `&nbsp;` I'll start doing this as well

2016-11-23 01:41 UTC, mistercrunch commented on superset/assets/javascripts/dashboard/components/SaveModal.jsx
> +            <input
We're trying to use react-bootstrap everywhere we can, check out https://react-bootstrap.github.io/components.html#forms

2016-11-23 01:43 UTC, ascott commented on superset/views.py
> +    @expose("/copy_dash/<dashboard_id>/", methods=['GET', 'POST'])
let's call this endpoint `copy_dashboard` for clarity

2016-11-23 01:44 UTC, ascott commented on superset/views.py
> +    @expose("/copy_dash/<dashboard_id>/", methods=['GET', 'POST'])
although i guess our save method also uses shorthand with `save_dash`, so nbd. can leave as is.

2016-11-23 01:44 UTC, mistercrunch commented
Oh please add python tests for the new endpoints, should be pretty straightforward. Some variation around:
https://github.com/airbnb/superset/blob/master/tests/core_tests.py#L232

You can disregard the JS tests for now as there's issues with building dashboard objects in the node test environment. I have to figure this out.

2016-11-23 23:54 UTC, the-dcruz commented
@mistercrunch @ascott Thank you for the feedback!

I've addressed all of your concerns. Pleases take a look when you get a chance 😄 Thanks!

2016-11-24 00:03 UTC, the-dcruz commented
![dash_save_as_3](https://cloud.githubusercontent.com/assets/1399237/20582476/4671e910-b196-11e6-8a0a-8ea6c872192f.gif)

2016-11-28 16:31 UTC, mistercrunch approved these changes

2016-11-28 16:34 UTC, mistercrunch commented
![img](https://media.giphy.com/media/cSc05Wc8WCtWg/giphy.gif)

2016-11-28 16:34 UTC, merged