feat(dashboard): Add description to the native filter
apache/superset pull request #17025
Opened 2021-10-07 20:17 UTC by m-ajay

### SUMMARY
Add a description column to the native filter. Show the description on hover.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
![tooltip](https://user-images.githubusercontent.com/12539911/136455698-891ec727-3a22-4ef2-b20a-076d243eac5e.gif)

### TESTING INSTRUCTIONS
1. Turn native filters feature flags ON
2. Open a dashbboard, and click edit native filters
3. Add help text to the description column
4. Save
5. Hover over the "i" icon to see the description

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Required feature flags: DASHBOARD_NATIVE_FILTERS, DASHBOARD_NATIVE_FILTERS_SET
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-10-07 20:22 UTC, graceguo-supercat commented
@m-ajay and @rusackas Please add design comments.

2021-10-14 11:58 UTC, michael-s-molina commented
The asterisk should come before the description icon for required filters.

<img width="243" alt="Screen Shot 2021-10-14 at 8 54 35 AM" src="https://user-images.githubusercontent.com/70410625/137312469-453d0d02-130a-4063-ba15-41836e5e0103.png">

2021-10-25 20:00 UTC, michael-s-molina requested changes
@m-ajay Requested some changes, especially about the use of the theme variable.

2021-10-27 18:28 UTC, michael-s-molina approved these changes
LGTM. Thanks for the contribution @m-ajay!

2021-10-27 18:45 UTC, merged