Take version from latest git tag, bump version in package.json
apache/superset pull request #17414
Opened 2021-11-12 02:58 UTC by mayurnewase

When installing superset, get version from latest tag.
If git not available, need to put correct tag in package.json to show correct version in ui.

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-11-12 03:18 UTC, mayurnewase commented on setup.py
> +    version_string = "1.3.2"  # current latest as last fallback
this may not be used.

2021-11-12 22:22 UTC, junlincc commented
Thank you so much @mayurnewase ! will test it locally.

2021-11-12 22:23 UTC, junlincc commented
/testenv up

2021-11-12 22:53 UTC, junlincc commented
looks like it only show the helm chart version? is it possible to show either 1.3.2 or latest master? 
<img width="261" alt="Screen Shot 2021-11-12 at 2 52 35 PM" src="https://user-images.githubusercontent.com/67837651/141581544-326426c6-a08a-45c4-96e4-f751dbfc806e.png">

2021-11-15 13:12 UTC, mayurnewase commented
it will take from latest release tag from github.
will update it to take it only what we put in package.json file,so we can put whatever we want.

2021-11-17 00:13 UTC, junlincc commented
@mayurnewase thank you! lmk when it's ready 🙏

2021-11-26 11:55 UTC, mayurnewase commented
@junlincc now it should show 1.3.2

2021-12-14 08:36 UTC, villebro requested changes
It seems the git-based automation was removed. I think it's important to distinguish a real release (1.3.2) from master branch or a custom tag/branch. I kinda liked using git for it; was there a reason for reverting that code?

2022-01-05 12:19 UTC, mayurnewase commented
@villebro  I had used `git describe --tags --abbrev=0` to get latest git tag available on current branch, but it showing helm charts tags as they were latest.
Should we do similar and filter by regex to show latest superset release tag?

2022-01-05 12:38 UTC, mayurnewase commented
Something like `git tag --sort=committerdate | tail -50 | grep -e "^\d" | tail -1`

2022-04-28 06:46 UTC, closed without merging