Fix: Line Chart Annotation Info Update
apache/superset pull request #19001
Opened 2022-03-02 19:32 UTC by codemaster08240328

### SUMMARY

In production annotation verbiage is a bit confusing for a new user. 
Feedback from Opendoor was to clarify that the chart being referenced is a chart created by the user/team.

Clear instruction should be needed.

```
Use another existing chart as a source for annotations and overlays.
Your chart must be one of these visualization types:...
```

![image](https://user-images.githubusercontent.com/39701522/156435505-4e02e01f-90e8-4fea-be04-f22eae5a7b00.png)

2022-03-03 18:45 UTC, rusackas requested changes

2022-03-03 18:45 UTC, rusackas commented on superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx
> +        description = `Use another existing chart as a source for annotations and overlays.
We should wrap this in `t()`

I'm not sure the line break is helping.

2022-03-10 04:12 UTC, rusackas commented on superset/translations/zh/LC_MESSAGES/messages.json
> +      "Use another existing chart as a source for annotations and overlays. Your chart must be one of these visualization types:": [
I think this would need to be the full string including the brackets and %s.

2022-03-10 04:14 UTC, rusackas commented on superset/translations/zh/LC_MESSAGES/messages.json
>          "使用预定义的图表作为注释和覆盖的源。图表必须是以下可视化类型之一："
```suggestion
      "Use another existing chart as a source for annotations and overlays. Your chart must be one of these visualization types: [%s]": [
        "使用预定义的图表作为注释和覆盖的源。图表必须是以下可视化类型之一：[%s]"
```

2022-03-10 04:21 UTC, rusackas commented on superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx
> +        );
If this seems to convoluted, you could do it like this:
```suggestion
        const supportedTypes = this.getSupportedSourceTypes(annotationType)
            .map(x => x.label)
            .join(', '),
        );
        const supportedTypesInstructions = t(
         `Use another existing chart as a source for annotations and overlays.
          Your chart must be one of these visualization types`
        );
        description = `${supportedTypesInstructions}: [{$supportedTypes}]`
```
... but either way works! ¯\\\_(ツ)_/¯

2022-03-11 17:49 UTC, codemaster08240328 commented on superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx
> +        );
Picked the previous one, to keep consistency. 

Thanks. 👍

2022-03-11 18:10 UTC, diegomedina248 approved these changes

2022-03-16 15:15 UTC, rusackas approved these changes
LGTM. Hopefully the CI Logjam will clear soon :)

2022-03-18 04:08 UTC, rusackas commented
@codemaster08240328 please rebase so this can pass CI.

2022-04-14 17:46 UTC, merged