fix(dashboard): make to show the correct owned objects
apache/superset pull request #19223
Opened 2022-03-16 18:52 UTC by prosdev0107

### SUMMARY
Making myself owner of a dashboard that was NOT created by me does not show in "Mine" tab on homepage

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE:
https://user-images.githubusercontent.com/47900232/158665539-27d39b54-a5a9-4207-83b7-0cf06a85ed34.mov

AFTER:
https://user-images.githubusercontent.com/47900232/158665158-be40dd12-9c51-4892-ad83-442266d15cc7.mov

### TESTING INSTRUCTIONS
**How to reproduce bugs**

1. Click the "Dashboards" tab
2. Hover over the actions panel
3. Click the "Edit" button
4. Make yourself the owner of the dashboard
5. Click the "Save" button
6. Go back to the "Home" page
7. Select the "Mine" section in "Dashboard" panel
8. Pay attention to the dashboards

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-03-17 03:18 UTC, diegomedina248 requested changes

2022-03-17 03:18 UTC, diegomedina248 commented on superset-frontend/src/views/CRUD/utils.tsx
> +        col: resource === 'saved_query' ? 'created_by' : 'owners',
this kind of defeats the purpose to me, and makes this function harder to reuse.
I would add a `col` and `opr` as third and fourth param, assigning the 'owners' and 'rel_m_m' as defaults.
Then, when calling for `saved_query`, we can override those, and reuse it for other calls if needed.

2022-03-18 17:52 UTC, prosdev0107 commented
@diegomedina248 

Can you review this PR and approve if it is good?

2022-03-21 21:38 UTC, diegomedina248 approved these changes

2022-03-21 21:48 UTC, rusackas approved these changes
LGTM

2022-03-21 21:51 UTC, merged

2022-03-25 08:44 UTC, villebro commented
@prosdev0107 @diegomedina248 After this PR I'm getting this error toast on the Welcome page: 
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/33317356/160086196-670d8724-2725-4ee1-8e4b-2853511264f5.png">

2022-03-25 10:02 UTC, diegomedina248 commented
@prosdev0107 please review, I am able to reproduce the error as well.
It happens on initial load, if you then switch filters it works.

2022-03-25 18:00 UTC, prosdev0107 commented
@diegomedina248 
I checked the this part code and I found that someone(I could see it from git history) made changes in this part after merging this PR.
I think that someone made the changes when rebase or merge master into his branch.