chore: Removes unused vars
apache/superset pull request #20194
Opened 2022-05-25 20:28 UTC by michael-s-molina

### SUMMARY
Removes unused vars to get rid of `no-unused-vars` warnings.

### TESTING INSTRUCTIONS
1 - Execute all tests
2 - All tests should pass

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-05-31 13:35 UTC, zhaoyongjie requested changes, later dismissed

2022-05-31 13:35 UTC, zhaoyongjie commented on superset-frontend/packages/superset-ui-chart-controls/src/operators/flattenOperator.ts
> -});
The operators in AA are intentionally designed to be a unified interface. These operators may use `formData` or `queryObject` at any time.

2022-05-31 13:35 UTC, zhaoyongjie commented on superset-frontend/packages/superset-ui-chart-controls/src/operators/flattenOperator.ts
> -});
The operators in AA are intentionally designed to be a unified interface. These operators may use `formData` or `queryObject` at any time.

2022-05-31 13:35 UTC, zhaoyongjie commented on superset-frontend/packages/superset-ui-chart-controls/src/operators/prophetOperator.ts
> -  const index = getColumnLabel(formData.x_axis || DTTM_ALIAS);
same before

2022-06-02 13:45 UTC, zhaoyongjie reviewed
Some comments from offline discussion:

------
Every operator generator receives 2 arguments to generate operator, the interface of PostProcessingFactory is

```typescript
export interface PostProcessingFactory<T> {
  (formData: QueryFormData, queryObject: QueryObject): T;
}
```

Even though we don’t use `formData` or `queryObject` in some operators, I suggest keeping the both arguments in function signature , if we remove them , each time a argument is added, then the `prettier` will reformat  the codes

2022-06-02 13:48 UTC, michael-s-molina commented
@zhaoyongjie I prefer to omit the parameters here just like any other function. Especially because it's clearly typed as `PostProcessingFactory` which allows the developer to easily check the available parameters. It's the same as a `forEach` where you have access to the `element` and `index` but often the `index` is omitted because it's not used.

Prettier will reformat the code the same way as it would for any other function. I don't think adding `eslint` ignores here is the way to go but curious to hear other opinions as well. @villebro @rusackas

2022-06-02 14:01 UTC, michael-s-molina commented
I really like the idea of reducing unnecessary changes but I don't think it's the case here. The variables are not being used, I don't think we should keep them to avoid a bigger diff during PR reviews. In fact, if one of these operators starts to use the arguments, then I would really like to see the signature change because it will clearly show that the variable is now being used.

2022-06-15 07:28 UTC, villebro reviewed
Great to see this cleanup! However, I agree with @zhaoyongjie 's comments about the unified signature for the post processing operators (they should be kept consistent)

2022-06-15 11:59 UTC, michael-s-molina commented
@zhaoyongjie @villebro I disabled the `no-unused-vars` lint rules for the operators to keep the interface as requested.

2022-06-15 12:40 UTC, villebro approved these changes
LGTM

2022-06-15 14:01 UTC, merged