fix: Alpha are unable to perform a second modification to a Dataset when in Explore
apache/superset pull request #20296
Opened 2022-06-07 17:58 UTC by hughhhh

### SUMMARY

Fix issue when Alpha users want to make a secondary change in `Edit Dataset`. The issue lies with the API from `datasource/save` returning a different payload for datasource.owners. To handle we'll add an additional check for the key value to make sure the user will still be able to edit moving forward.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-06-07 18:20 UTC, pkdotson approved these changes
Lgtm!

2022-06-07 18:24 UTC, AAfghahi requested changes

2022-06-07 18:24 UTC, AAfghahi commented on superset-frontend/src/explore/components/controls/DatasourceControl/index.jsx
> +      datasource.owners.map(o => o.value).includes(user.userId);
couldn't you write this in without the ||

`o => o.id || o.value == user.userId `

2022-06-07 18:24 UTC, AAfghahi commented on superset-frontend/src/explore/components/controls/DatasourceControl/index.jsx
> +      datasource.owners.map(o => o.value).includes(user.userId);
don't think this is the right way of doing it though.

2022-06-07 18:25 UTC, AAfghahi commented on superset-frontend/src/explore/components/controls/DatasourceControl/index.jsx
> +      datasource.owners.map(o => o.value).includes(user.userId);
also should this be an || or should you be amending allowEdit with the new values from o.value?

2022-06-07 18:42 UTC, hughhhh commented
/testenv up

2022-06-08 13:28 UTC, AAfghahi approved these changes
could we add some tests for this?

2022-06-08 14:24 UTC, merged