chore(deps): pinning pyjwt to 2.4.0
apache/superset pull request #20297
Opened 2022-06-07 18:16 UTC by sadpandajoe

### SUMMARY
Missed a spot with https://github.com/apache/superset/pull/20287 where we were still using a lower version of pyjwt. 
Here is the change log for version [2.4.0](https://pyjwt.readthedocs.io/en/latest/changelog.html#v2-4-0) that we are moving to.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-06-07 18:17 UTC, AAfghahi approved these changes

2022-06-07 18:54 UTC, hughhhh commented on setup.py
> +        "PyJWT>=2.4.0",
put <3.0.0

2022-06-07 18:55 UTC, AAfghahi requested changes

2022-06-07 18:55 UTC, AAfghahi commented on setup.py
> +        "PyJWT>=2.4.0",
`PyJWT>=2.4.0, <3.0`,

2022-06-07 20:07 UTC, AAfghahi commented on setup.py
> +        "PyJWT>=2.4.0", <3.0,
```suggestion
        "PyJWT>=2.4.0, <3.0",
```

2022-06-08 01:33 UTC, AAfghahi approved these changes

2022-06-08 01:34 UTC, merged

2022-06-08 16:15 UTC, sadpandajoe commented
🏷️ preset:2022.23