fix: A newly connected database doesn't appear in the databases list if user connected database using the 'plus' button
apache/superset pull request #20363
Opened 2022-06-13 18:17 UTC by diegomedina248

### SUMMARY

The RightMenu currently uses the `useQueryParam` hook that needs a Provider to wrap it (much like the redux store provider, theme provider, etc).

Currently, we have more that one entry point (App.tsx/js) and they don't have the same structure.
Long term solution is to unify these into a single entry point, or at least, have the same provider structure for commonly used tools.

This PR enables the useQueryParam in said component if the router is available, and otherwise ignores it.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
-

### TESTING INSTRUCTIONS
Ensure that, adding a database from the + menu works.
Ensure the explore loads correctly.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-06-13 20:41 UTC, AAfghahi requested changes
This is good! But I think that we should include a test with the plus button to make sure that it is working.

2022-06-13 20:41 UTC, AAfghahi commented
/testenv up

2022-06-13 22:19 UTC, prosdev0107 commented
LGTM!

2022-06-14 08:31 UTC, stephenLYZ commented on superset-frontend/src/views/components/MenuRight.tsx
> +class RightMenuErrorWrapper extends React.PureComponent<RightMenuProps> {
Can we add some comments here? Others may be curious as to why an additional error wrapper is needed.

2022-06-14 18:55 UTC, AAfghahi approved these changes

2022-06-14 23:47 UTC, merged