fix: Bar stacking on v2 doesn't work if the x-axis is value type
apache/superset pull request #20591
Opened 2022-07-01 23:59 UTC by diegomedina248

### SUMMARY

When `GENERIC_CHART_AXES` is enabled, stacking on bar chart v2 is not working correctly in all cases.
The reason is that bar stacking is supported by echarts only for categorical types.
Source: https://github.com/apache/echarts/issues/15102

This PR hides that feature if the axis is not categorical.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

https://user-images.githubusercontent.com/17252075/176978590-653b4411-ed1a-4e1f-a0a9-d138b6091b29.mov

After:

https://user-images.githubusercontent.com/17252075/176978651-8ff74bd7-45f6-49d8-9641-11d635317692.mov

### TESTING INSTRUCTIONS
1. Enable `GENERIC_CHART_AXES`.
2. Create Bar v2 charts with different types in the x-types.

Ensure the stack option is only available for categorical types, and that it works as expected.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-07-04 02:57 UTC, zhaoyongjie commented
/testenv up

2022-07-04 03:25 UTC, zhaoyongjie commented
/testenv up FEATURE_GENERIC_CHART_AXES=true

2022-07-04 03:46 UTC, zhaoyongjie requested changes
The root cause of the case was multiple metrics applied in the stack bar chart. 
1. The bar chart in the Echart supports timeseries as the x-axis to stack. e.g.

https://user-images.githubusercontent.com/2016594/177077660-b9ae1222-bd66-4f9f-8bcc-e7e92e1cf7ad.mov


2. we should find a way to support multiple metrics in the bar chart, or just avoid applying multiple metrics in the stacked bar chart, **instead of removing the entire stack feature in the timeseries barchart**.

2022-07-27 19:15 UTC, rusackas commented
@diegomedina248 @zhaoyongjie should we set up a time to sync on this and get to the bottom of it?

2022-08-10 15:35 UTC, diegomedina248 commented
Closed in favor on #20805

2022-08-10 15:35 UTC, closed without merging