docs: Add BurdaForward to "In the Wild" and merge "News" and "Entertainment" to "Media & Entertainment"
apache/superset pull request #24339
Opened 2023-06-09 08:26 UTC by mattitoo

### SUMMARY

 Add BurdaForward to "In the Wild" and merge "News" and "Entertainment" to "Media & Entertainment"

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

Check the page if link for BurdaForward works

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2023-06-09 08:59 UTC, villebro requested changes
Thanks for the addition - one minor comment about ordering, other than that LGTM

2023-06-09 08:59 UTC, villebro commented on RESOURCES/INTHEWILD.md
> +- [BurdaForward](https://www.burda-forward.de/en/)
Please place the entries in ABC order

2023-06-09 11:13 UTC, villebro approved these changes
LGTM

2023-06-09 11:13 UTC, merged

2026-01-10 00:13 UTC, rusackas commented
Feel free to update the new [yaml file](https://github.com/apache/superset/edit/master/RESOURCES/INTHEWILD.yaml) if you want to upload a logo or add additional github handles!