Alternative PR for: Some bytes/str issues in py3 w/ zlib and json
apache/superset pull request #2558
Opened 2017-04-05 16:19 UTC by rumbin

This is in essence the same as #2034, however, it is rebased now and reduced to what is really needed.

2017-04-05 17:06 UTC, mistercrunch requested changes

2017-04-05 17:06 UTC, mistercrunch commented on tests/utils_tests.py
> +        got_str = zlib_uncompress_to_string(blob)
`zlib_decompress_to_string` this is what breaks the build

2017-04-05 17:06 UTC, mistercrunch commented on superset/utils.py
> +def zlib_compress(data):
too many blank lines, should be 2 blank lines above a function (PEP8)

2017-04-05 17:06 UTC, mistercrunch commented on superset/utils.py
> +
remove blank line

2017-04-05 18:39 UTC, xrmx commented on superset/utils.py
> +        decompressed = ""
You don't need this

2017-04-05 18:42 UTC, xrmx commented on superset/utils.py
> +        if isinstance(decompressed, str):
python3 documentation says that zlib.decompress returns bytes

2017-04-05 18:46 UTC, xrmx commented on superset/utils.py
> +        else:
We may put a return zlib.compress(data) outside the if PY3K instead of the following 4 lines.

2017-04-06 07:52 UTC, xrmx commented on superset/utils.py
> +        else:
You can drop the else, it'll we handled by the last return

2017-04-06 16:42 UTC, mistercrunch commented
Thanks for getting this through!

2017-04-06 16:42 UTC, merged