feat: Funnel/tooltip-customization
apache/superset pull request #25666
Opened 2023-10-16 17:29 UTC by CorbinBullard

### SUMMARY

Added customization to funnel chart tooltips as well as the option to disable the tooltip 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

BEFORE:
![Clipboard 2023-16-06 at 4 10 21 PM](https://github.com/apache/superset/assets/11916151/b06a5518-ccca-460e-9e7c-486055728c07)
AFTER:
![Funnel-tootip-functionality](https://github.com/apache/superset/assets/11916151/a474a397-7e7f-40d3-ab2c-a220c28e5914)

2023-10-18 22:52 UTC, yousoph commented
/testenv up

2023-10-18 23:23 UTC, yousoph commented
Could you update the default for the tooltip contents to be "Category, Value, and Percentage" so it's in line with what the tooltips contain today?

2023-10-19 05:01 UTC, Youlijianxin approved these changes

2023-10-19 11:38 UTC, michael-s-molina requested changes
Thank you for the improvement @CorbinBullard. I left some first-pass comments.

2023-10-19 11:38 UTC, michael-s-molina commented on superset-frontend/plugins/plugin-chart-echarts/src/Funnel/transformProps.ts
> +      show: showTooltipLabels,
`inContextMenu` is used to avoid showing the tooltip when right clicking.
```suggestion
      show: !inContextMenu & showTooltipLabels,
```

2023-10-19 11:38 UTC, michael-s-molina commented on superset-frontend/plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
> +              default: EchartsFunnelLabelTypeType.KeyValuePercent,
Could you make sure the defaults come from `DEFAULT_FORM_DATA`?

2023-10-19 11:38 UTC, michael-s-molina commented on superset-frontend/plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
> +              description: t('What should be shown on the tooltip Label?'),
Could you make sure the descriptions are not questions for all controls? It will be more consistent with other plugins?

2023-10-19 14:32 UTC, michael-s-molina commented on superset-frontend/plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
> +              description: t('What should be shown on the tooltip Label'),
```suggestion
              description: t('What should be shown as the tooltip label'),
```

2023-10-19 14:32 UTC, michael-s-molina commented on superset-frontend/plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
> +              description: t('What should be shown on the label'),
```suggestion
              description: t('What should be shown as the label'),
```

2023-10-19 14:48 UTC, michael-s-molina commented on superset-frontend/plugins/plugin-chart-echarts/src/Funnel/controlPanel.tsx
> +              description: t('What should be shown as the tooltip Label'),
```suggestion
              description: t('What should be shown as the tooltip label'),
```

2023-10-19 14:56 UTC, michael-s-molina approved these changes
LGTM. Thanks for the improvement @CorbinBullard!

2023-10-19 18:04 UTC, merged

2023-11-06 16:39 UTC, MariusMunder commented
This is an awesome feature. Can this be extended to all popular charts?

2024-02-01 20:58 UTC, rusackas commented
> This is an awesome feature. Can this be extended to all popular charts?

I hate to be "that guy" on the open-source project, but we'd be happy to review PRs for this from you or anyone reading this. Hopefully this can be followed up on as an example implementation.

2025-01-15 04:25 UTC, MilenioScience commented
How to add customization to line chart tooltips, right now the line chart tooltips only have check/no check value of rich tooltip. I want to only display the actual value not the total nor percentage