feat(maps): Consolidating all country maps (and TS) into the Jupyter notebook workflow.
apache/superset pull request #26300
Opened 2023-12-18 18:59 UTC by rusackas

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2023-12-18 21:19 UTC, rusackas commented
/testenv up

2023-12-27 03:24 UTC, phobal commented on superset-frontend/package.json
> +    "update-maps": "jupyter nbconvert --to notebook --execute --inplace 'plugins/legacy-plugin-chart-country-map/scripts/Country Map GeoJSON Generator.ipynb' -Xfrozen_modules=off"
missing a comma

2023-12-27 05:56 UTC, rusackas commented on superset-frontend/package.json
> +    "update-maps": "jupyter nbconvert --to notebook --execute --inplace 'plugins/legacy-plugin-chart-country-map/scripts/Country Map GeoJSON Generator.ipynb' -Xfrozen_modules=off"
quite right, thanks!

2024-01-27 03:51 UTC, villebro requested changes
As a Finn this caught my eye - apparently `Åland Islands` has been replaced by `Åland` in the dataset. Can you replace the following snippet:
```python
finland_aland = df_admin0_10m.loc[
    df_admin0_10m.name_en.isin(['Åland Islands']),
    [x for x in df_admin0_10m.columns if x in df.columns]
]
finland_aland = finland_aland.merge(pd.DataFrame(
    data={
        "name_en": ["Åland Islands"],
        "name_fi": ["Ahvenanmaan maakunta"],
        "iso_3166_2": ["FI-01"],
    },
), on="name_en", how="left")
```

with

```python
finland_aland = df_admin0_10m.loc[
    df_admin0_10m.name_en.isin(['Åland']),
    [x for x in df_admin0_10m.columns if x in df.columns]
]
finland_aland = finland_aland.merge(pd.DataFrame(
    data={
        "name_en": ["Åland"],
        "name_fi": ["Ahvenanmaan maakunta"],
        "iso_3166_2": ["FI-01"],
    },
), on="name_en", how="left")
```

This will ensure that the Finnish southwestern archipelago looks correct.

Before:
<img width="399" alt="image" src="https://github.com/apache/superset/assets/33317356/783d7c98-624c-45ee-bb44-6d727c8451f0">

After:
<img width="439" alt="image" src="https://github.com/apache/superset/assets/33317356/cab5bc2a-83c5-4de8-b04a-e62be7334845">

2024-01-29 18:13 UTC, rusackas commented
@villebro done!

2024-01-30 22:19 UTC, qleroy commented
@rusackas 

About france_regions the meltdown is due to the projection used, I added detailed explanation in the PR that added this #25676 

and @dmeaux proposed a fixed geojson file #26848

2024-01-30 22:34 UTC, qleroy commented
To consolidate the geojson generation with the notebook,
I suggest to explicitly project the data with the WGS84 (EPSG:4326) project so that it is consistent,
https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_crs.html

This could also be a step in the documentation to note that it is required to provide files projected with WGS84

2024-01-30 23:00 UTC, qleroy commented
Also, I would love that we include overseas islands for France !
I don't understand why there were removed in the first place
while the flying islands were moved closer for other countries.

2024-01-30 23:06 UTC, villebro approved these changes
LGTM!

2024-01-30 23:06 UTC, villebro commented
@qleroy would you be open to contributing the floating islands for the French maps? That would be awesome! 🇫🇷

2024-01-30 23:26 UTC, rusackas commented
Happy to keep iterating on this, and indeed would love help with any of it! Meanwhile, let's merge this swath of it, so others can fork and contribute :) Thanks!

2024-01-30 23:26 UTC, merged

2024-02-02 17:02 UTC, qleroy commented
@villebro @rusackas 
I just updated the France map to include overseas islands !
#26995

2024-04-04 13:45 UTC, zufolo441 commented
Hi all,
is there a way to view deck.gl polygons same way as country maps, without any background map?
I used to use country maps, but now I have some maps in PostGIS database and they show in different ways....

thanks!