fix(chart table in dashboard): improve screen reading of table
apache/superset pull request #26453
Opened 2024-01-11 01:10 UTC by ncar285

### SUMMARY
Enhancing Accessibility with Unified Table Structure and Sticky Header

This PR addresses accessibility concerns by merging the header and body of our tables into a single unified structure. This change significantly improves screen reader compatibility, ensuring a more inclusive user experience. Previously, the header and body of a chart were seperate tables. Visually this worked but caused issues with screen reader functionality.

**Key Change:**
- The table now consists of a single, unified structure, as opposed to separate elements for the header and body. This enhances accessibility, particularly for screen reader users.
- The header is made sticky using CSS, allowing it to remain visible while the table body is scrollable.

**Technical Challenge:**
A notable challenge was maintaining a scrollable body while keeping the header fixed. Setting overflow directly on **`tbody`** proved unfeasible. Wrapping **`tbody`** in a div with an overflow disrupted the column grouping, as the table would then interpret the entire **`tbody`** as a single column. The implemented solution achieves the desired layout without compromising the table's integrity or accessibility.

### TESTING INSTRUCTIONS

1. Navigate to a page featuring the modified table structure.
2. Use a screen reader to ensure that the table content is read correctly and in a logical order and doesn't read end of table early.
3. Scroll through the table to check that the header remains fixed while the body is scrollable.
4. Visually inspect the table across different browsers for consistent rendering.

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/26177
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2024-01-11 23:20 UTC, eschutho commented
@ncar285 looks like there are some linting errors that are causing the tests to fail. I can comment on some in the PR, but you can also run `npm run lint-fix` from superset-frontend folder and that will catch some of the indentation ones.

2024-01-12 00:06 UTC, eschutho commented on superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
> +      {/* {headerTable} */}
```suggestion
```

2024-01-12 00:11 UTC, eschutho requested changes
Thanks @ncar285! Looks really good. Just some small suggestions for linting and cleanup.

2024-01-12 00:11 UTC, eschutho commented on superset-frontend/plugins/plugin-chart-table/src/Styles.tsx
> +      border-bottom: 2px solid #e0e0e0;
```suggestion
      border-bottom: ${theme.gridUnit /2}px solid ${theme.colors.grayscale.light2};
```
you'll want to use the theme here for styling when possible

2024-01-12 00:11 UTC, eschutho commented on superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
> +  // let bodyTable: ReactElement | undefined;
```suggestion
  // let bodyTable: ReactElement | undefined;
```

2024-01-12 00:11 UTC, eschutho commented on superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
> +
```suggestion

```

2024-01-12 00:11 UTC, eschutho commented on superset-frontend/plugins/plugin-chart-table/src/DataTable/DataTable.tsx
> +
```suggestion

```

2024-01-19 04:40 UTC, yousoph commented
/testenv up

2024-01-20 00:39 UTC, eschutho approved these changes
This looks great @ncar285. I'll leave the PR open for testing, and then we'll merge. Thank you!

2024-01-29 19:05 UTC, merged

2024-01-31 16:02 UTC, kgabryje commented
@ncar285 @eschutho I think after this PR the Totals are not sticky anymore 🙁 

https://github.com/apache/superset/assets/15073128/e58fdb5e-7702-4cce-a318-2a876a091a49