chore(docs): bump version number in docs example
apache/superset pull request #27038
Opened 2024-02-07 14:15 UTC by sfirke

### SUMMARY
There are example version numbers in the Alerts & Reports docs listed as 2.0.1. At least one new user took this as a sign that this page was stale. It is not. I am bumping it to 3.1.0 to make that clearer.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2024-02-07 19:26 UTC, rusackas approved these changes
Thanks!

2024-02-08 00:11 UTC, mistercrunch commented
Is there an easy way in docausurus "templatize" and use a variable like `{{ latest_asf_version }}` so that we could just bump in one place and add a note to bump this variable as part of the release process?

2024-02-08 00:27 UTC, mistercrunch requested changes
Setting to "Request changes" as otherwise it'll get stale or force us to grep + multi-update at every release... This also sets a new pattern to keep the docs more dynamic, worth doing if we can figure this out quickly.

2024-02-08 05:47 UTC, rusackas commented
I'm fine with letting this through and following up on a fancier version. For getting fancy, we need to differentiate between latest _stable_ (i.e. not a major x.0.0) and _latest_, so doing it as part of the release process might not work the way we want.

We _could_ make a little script as a "prebuild" step for docusaurus, so that whenever it builds, it scrapes GitHub (or Apache, potentially) for all the latest releases, and saves a little JSON object like :

```
{
  latest: 'x.x.x',
  latest_stable: 'x.x.x',
  latest_major: 'x.0.0',
  latest_minor: 'x.x.0',
  latest_patch: 'x.x.x',
  lts: 'x.x.x'
}
```

This could then be directly included in any MDX page to spit out whatever we want.

2024-02-08 08:59 UTC, mistercrunch approved these changes

2024-02-08 15:47 UTC, rusackas commented
We have a task board for Documentation. I'll put this idea on there for a rainy day :)

2024-02-08 15:47 UTC, merged