update Michigan polygon
apache/superset pull request #29503
Opened 2024-07-05 15:20 UTC by jpmonette

### SUMMARY

The purpose of this PR is to refine the look & feel of the Michigan state on the `legacy-plugin-chart-country-map`, so the polygon does not include one of the great lakes.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

#### Before

![image](https://github.com/apache/superset/assets/1114325/955193aa-03c2-4f90-a7a0-34a36f83c694)

#### After

![image](https://github.com/apache/superset/assets/1114325/7582d9d8-7a15-4ac4-b833-b8367d959153)

### TESTING INSTRUCTIONS

1. Create chart
2. Pick Country Map
3. Select US
4. Select any metrics / ISO
5. Generate US Map

### ADDITIONAL INFORMATION

- [ ] Has associated issue: https://github.com/apache/superset/issues/29485
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2024-07-07 04:54 UTC, rusackas commented
Well, that's odd... both that it happened, and that nobody has complained! 

The help here is much appreciated, but could you make the change via the Jupyter Notebook? Changes made directly to geojson files are doomed to be overwritten. [Hope this helps](https://www.notion.so/preset/How-and-When-and-Why-to-Update-Superset-Country-Maps-10a6731037cf4cd38517a4ff0a7e66ec#fe87073befd84bc9978adf98faec16f8).

2024-07-09 14:03 UTC, jpmonette commented
@rusackas This seems to be private Notion content.

![Capture d’écran, le 2024-07-09 à 15 03 15](https://github.com/apache/superset/assets/1114325/57d32dbb-6165-41dc-b271-f7462dc30ab9)

2024-07-09 19:15 UTC, rusackas commented
Hah, that's because I accidentally sent the draft content, not the actual published post! Sorry 😊 

https://preset.io/blog/how-and-when-and-why-to-update-apache-supersets-country-maps/

2025-03-22 17:49 UTC, rusackas requested changes
I'm not sure if this is still an issue with the current map data (it's more than a bit old at this point), but any changes made to the GeoJSON would be overwritten by the Jupyter notebook that generates them, so we'll need to make changes in the `.ipynb` file first. Here's some info on the topic: https://preset.io/blog/how-and-when-and-why-to-update-apache-supersets-country-maps/

2025-06-16 22:28 UTC, rusackas commented
Any hopes of getting the Jupyter notebook updated so we can merge the (resulting) GeoJSON?

2025-12-11 20:09 UTC, rusackas commented
This still needs to be done via the Jupyter notebook. Converting to draft for now, but would love to see this touched up so we can review/merge!

2026-04-27 16:09 UTC, rusackas commented
Took another look at this in the context of #29485. Quick status for anyone picking it up:

The maintainer ask on the linked issue is to land the fix via the Jupyter notebook (`superset-frontend/plugins/legacy-plugin-chart-country-map/scripts/Country Map GeoJSON Generator.ipynb`) rather than as a one-off manual edit to `usa.geojson`, so future regenerations don't undo it. The cleanest path is probably to add a Great Lakes clipping step to the USA section of the notebook (subtract `ne_10m_lakes` from the Great Lakes states' geometries), then re-run the notebook to regenerate `usa.geojson`.

Reference for context: https://preset.io/blog/how-and-when-and-why-to-update-apache-supersets-country-maps/

If you don't have time to set up the geopandas/Natural Earth env to regen, leaving this draft up is still useful as a reproducer — happy to coordinate with anyone willing to run the notebook.

2026-06-23 16:06 UTC, rusackas commented
@jpmonette this is a legit fix (#29485 is still open) but the geojson edit gets overwritten on regeneration, so it has to go through the Jupyter notebook generator. You've been quiet, so I can see about redoing it that way unless you want to take another crack.

2026-06-27 04:23 UTC, rusackas commented
@jpmonette since you've gone quiet so I'll attempt to redo the Michigan fix through the notebook generator so it survives regeneration, but holler if you'd rather finish it yourself.

2026-07-23 01:28 UTC, rusackas commented
Redid this through the notebook generator so the fix survives regeneration: the USA map is sourced from Natural Earth's `_lakes` dataset variant, which carves the lakes out of the state polygons. Michigan gets its mitten back, and Wisconsin/Minnesota/New York stop painting their share of the lakes too.

Also merged current `master` into the branch while I was in there. Marked it ready for review, and CI's running 🤞 Thanks for the patience here @jpmonette!

2026-07-25 09:41 UTC, rusackas approved these changes
Notebook regen looks right — Great Lakes carved out, Michigan/Wisconsin/Minnesota/New York fixed, CI green. Thanks for the original report and patience, @jpmonette.

2026-07-28 02:58 UTC, merged