improve pdf export quality
apache/superset pull request #31349
Opened 2024-12-09 13:33 UTC by tahvane1

This PR uses img2pdf to export charts to pdf. Current solutions uses compression in such way that pdf is grainy.
Using img2pdf removes this issue mostly.

### SUMMARY
Current pdf quality is poor and this improves it significantly

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS
img2pdf needs to be added to docker images.

### ADDITIONAL INFORMATION

2024-12-09 17:19 UTC, villebro requested changes
This PR apparently adds a new requirement. I don't oppose this change, but I would propose the following:
- Add `img2pdf` to one of the `.in` files in `requirements/`. Based on this change it would need to go into `base.in`. Also do check that the license is Apache 2.0 compliant.
- Add before/after screenshots to show how quality changes.
- Add info about how the pdf file size changed before/after. Lossless compression is great, but can bloat the attachment size.

2024-12-09 17:40 UTC, tahvane1 commented
img2pdf is using GNU Lesser General Public License v3 and it seems that it is not accepted in ASF projects. So need to look for alternative approach then.

2024-12-09 18:27 UTC, villebro commented
> img2pdf is using GNU Lesser General Public License v3 and it seems that it is not accepted in ASF projects. So need to look for alternative approach then.

Dang, that's a real shame! 🙁

2024-12-09 18:41 UTC, rusackas commented
Do we know if the low resolution is caused by the capture method (`Image.open(BytesIO(snap))`) or by the output method (`images[0].save(...)`)? Apparently if it's the latter, you can add a `resolution=300.0` parameter.

2024-12-09 21:28 UTC, tahvane1 commented
Resolution does not fix issue. I can get similar quality by setting quality=100 but this results to a pdf that has double the size what img2pdf produces. I will continue my testings...

2024-12-11 17:55 UTC, villebro commented
FYI I converted this to draft. @tahvane1 please feel free to change it back to non-draft if you find a new ASF-compliant way to fix this issue.

2025-01-14 16:47 UTC, closed without merging