[druid] Allow custom druid postaggregators
apache/superset pull request #3146
Opened 2017-07-17 11:32 UTC by brianwolfe

Fix the postaggregation for approxHistogram quantiles so it adds
the dependent field and that can show up in the graphs/tables.

In general, postAggregators add significant power, in developing custom
postAggregators, I've run into barriers integrating with Superset. Plywood
and other Druid query planners typically have escape hatches to specify
custom postAggregators without requiring a custom type definition for each
one.

This commit adds a similar capability for Superset and a additional
field/fields/fieldName breakdown of the typical naming for dependent
aggregations, which should make it significantly easier to develop
approxHistogram and custom postAggregation-required dashboards.

This should be able to supercede:
https://github.com/apache/incubator-superset/pull/2345
since it is strictly more general.

This should at least pull in the right dependent metrics and allow some custom aggregations and quantile/histogram links. @mistercrunch

2017-07-17 12:30 UTC, xrmx commented
Could please fix tests with python2.7 and remove all the other unrelated changes you did in the PR please?

2017-07-17 20:43 UTC, brianwolfe commented
Not sure what happened with that, it wasn't in my commit history. Fixed via rebase, will fix remaining python2 issues shortly, when I can get duplication on my local machine.

2017-07-18 15:32 UTC, brianwolfe commented
@xrmx, sorry for the busted PR earlier. This should be good to go (assuming my local testing and Travis agree).

I pulled the helper function out so I could actually unit test the dependent-data extraction/naive query planning. It'll be a significantly larger scope of testing changes if I put that back.

2017-07-18 15:55 UTC, brianwolfe commented
Attempting to rerun travis to get coveralls passing.

2017-07-20 23:55 UTC, brianwolfe commented
@xrmx or @mistercrunch PTAL This PR has passed Travis https://travis-ci.org/apache/incubator-superset/builds/254976199 (aside from the untouched JS build) and coveralls looks good: https://coveralls.io/builds/12486731

2017-07-27 15:22 UTC, brianwolfe commented
Resetting travis build again. Hopefully this all passes so that this can be merged in.

2017-07-27 20:23 UTC, mistercrunch requested changes
This is neat, thanks for the PR! 

So can post aggregators build upon other post aggregators? Seems like it's supported here and want to make sure Druid allows for that.

2017-07-27 20:23 UTC, mistercrunch commented on superset/connectors/druid/models.py
> +            _field = _conf.get('field', None)
`, None` is implicit, that's the default behavior

2017-07-27 20:23 UTC, mistercrunch commented on superset/connectors/druid/models.py
> +                        None,
it would help readability to use keyword args here

2017-07-27 20:23 UTC, mistercrunch commented on superset/connectors/druid/models.py
> +    def run_query(  # noqa / druid
I'm not sure why git is getting the diffing all wrong here, things are not lining up. Makes it hard to see what has changed in this section. Maybe moving `_metrics_and_post_aggs` higher / lower in the class definition might help git diffing it right?

2017-07-27 20:23 UTC, mistercrunch commented on superset/connectors/druid/models.py
> +        return all_metrics, post_aggs
I'm never a big fan of returning tuples but I think it's ok in this case

2017-07-27 20:23 UTC, mistercrunch commented on superset/connectors/druid/models.py
> +            if _field is not None:
`if _field:` is the pythonesque convention

2017-07-27 20:23 UTC, mistercrunch commented on superset/connectors/druid/models.py
> +            if _fields is not None:
why not use the same if block as the one right above this one?

2017-07-27 21:48 UTC, brianwolfe commented on superset/connectors/druid/models.py
> +            if _fields is not None:
_field vs _fields.

2017-07-27 21:48 UTC, brianwolfe commented on superset/connectors/druid/models.py
> +            if _field is not None:
I suppose. I prefer to be explicit when I care about None vs. when I want to reject all falsy values. https://docs.python.org/2.4/lib/truth.html

I'll change the PR.

2017-07-27 21:51 UTC, brianwolfe commented on superset/connectors/druid/models.py
> +            if _field is not None:
https://www.python.org/dev/peps/pep-0008/#programming-recommendations

2017-07-28 04:35 UTC, brianwolfe commented
@mistercrunch Yes, postAggregators can reference other postAggregators. The dataSketches library is rather incredible if you haven't looked at it before: https://datasketches.github.io/

They combine PostAggregators extensively to compute interesting results.

https://github.com/druid-io/druid/blob/master/extensions-core/datasketches/src/main/java/io/druid/query/aggregation/datasketches/theta/SketchSetPostAggregator.java#L49

Typically they are combined by FieldReference, but not always. In general, we'd probably want a real query planner here, but this allows us to use approxHistograms, dataSketches and other libraries without friction for now.

2017-07-28 04:38 UTC, brianwolfe commented on superset/connectors/druid/models.py
> +            if _fields is not None:
this is mostly a matter of supporting a newer and older postAggregators that have different customs for storing the dependent fields.

2017-07-28 04:39 UTC, brianwolfe commented on superset/connectors/druid/models.py
> +                        None,
fixed by making a CustomPostAggregator class that encompasses this logic. Should make more sense that way.

2017-07-28 04:39 UTC, brianwolfe commented on superset/connectors/druid/models.py
> +        return all_metrics, post_aggs
yeah, for an internal api, I feel like it's kinda defensible.

2017-07-28 04:40 UTC, brianwolfe commented on superset/connectors/druid/models.py
> +    def run_query(  # noqa / druid
moved up to other static methods.

2017-07-28 18:45 UTC, mistercrunch commented
This LGTM at this point. We'll need to validate in staging that existing slices that make use of postaggregators still compute well.

2017-07-28 18:46 UTC, merged