refactor(bulk_select): Fix bulk select tagging issues for users
apache/superset pull request #31631
Opened 2024-12-27 11:13 UTC by LevisNgigi

### SUMMARY
This PR addresses an issue where  users were unable to tag objects despite having the necessary permissions. The changes ensure that the tagging functionality correctly validates user ownership or edit permissions and allows tagging where applicable. Additionally, it refines error handling to avoid unnecessary warnings while maintaining robust validation for invalid objects.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS
1. Create a saved query
2. Go to saved query tab
3. Click bulk select
4. Select the created query
5. Click Add Tag
6 .Add any tag
Note that you'll need to have the feature flag TAGGING_SYSTEM enabled and create a tag in the Tags page (in Settings) first before going through the repro steps.

### ADDITIONAL INFORMATION

- [ x] Has associated issue:Fixes #27988
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2025-01-07 11:43 UTC, geido commented
Hey. Thanks for this. Do you think we could add tests to avoid the issue will be reintroduced in the future?

2025-01-09 10:37 UTC, geido requested changes
@LevisNgigi Something is off. When trying to bulk select and add a tag, instead of adding the existing tag, it is creating an entirely new tag. Can you please check that? 


https://github.com/user-attachments/assets/0dbe58cc-7f1a-4484-83d7-b15695389274

2025-01-09 13:43 UTC, LevisNgigi commented
> @LevisNgigi Something is off. When trying to bulk select and add a tag, instead of adding the existing tag, it is creating an entirely new tag. Can you please check that?
> 
>  DEV.Superset.mp4

@geido Thank you, I have fixed the bug.

2025-01-13 16:29 UTC, geido approved these changes
Did a bit of manual testing and looks fine. However, I find the user experience to be very odd here as once I have added a tag I cannot remove it. I think there should be an option somewhere for that in the future. Thanks for working on this.

2025-01-13 16:30 UTC, merged

2025-01-13 16:53 UTC, LevisNgigi commented
> Did a bit of manual testing and looks fine. However, I find the user experience to be very odd here as once I have added a tag I cannot remove it. I think there should be an option somewhere for that in the future. Thanks for working on this.

@geido Thank you for this. Also you can remove the tag from a query via the edit tag option.