[Add] add optional selection for filter order
apache/superset pull request #3285
Opened 2017-08-13 15:57 UTC by RoganW

Add a chance to change the order of optional value. 
When left empty, it will order the optional value by metric.

![2017-08-13 23 52 45](https://user-images.githubusercontent.com/7597155/29251140-a97b49dc-8082-11e7-9367-4c09ca36aef5.gif)

2017-08-13 16:02 UTC, mistercrunch commented
It's a bit better than before, but ultimately we'll want for each filter to be able to specify its own metric (or no metric at all) and its own ordering preference.

2017-08-13 16:25 UTC, RoganW commented
@mistercrunch Yeah, I think your proposal is more reasonable.
I'll optimize that later.

2017-08-13 17:38 UTC, RoganW commented
@mistercrunch Already optimized

2017-08-13 19:16 UTC, mistercrunch commented
What I'm proposing would be much more complicated. We may want to just land this as it is in the meantime.

2017-08-15 01:17 UTC, mistercrunch commented on superset/assets/backendSync.json
> +      "label": "Order by optional value",
`"Ordering"`

2017-08-15 01:22 UTC, mistercrunch requested changes

2017-08-15 01:22 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    multi: true,
shouldn't this be false?

2017-08-15 01:22 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +      choices: (state.datasource) ? state.datasource.order_by_choices : [],
shouldn't the option be `alphabetically`, `by metric descending`, and `by metric ascending`?

2017-08-15 01:22 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    'When does\'t select for one filter, it will order the optional value by metric.',
use `"` when string contains apostrophe `'`

2017-08-15 01:22 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    description: 'The way to order tho optional value of filters. ' +
tho -> the

2017-08-15 01:22 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    description: 'The way to order tho optional value of filters. ' +
"How to order the list of values for the filter"

2017-08-15 14:03 UTC, RoganW commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    multi: true,
Via setting `true`, we can specify ordering preference for each filter.

2017-08-15 14:46 UTC, RoganW commented on superset/assets/javascripts/explore/stores/controls.jsx
> +      choices: (state.datasource) ? state.datasource.order_by_choices : [],
I think, in most cases, users know which option they want to choose, and we just need to help them to find it quickly. so, be `alphabetically` and be `reverse order` are used more often than `by metric descending`. 
For example, area(alphabetically) and period(like year-month in reverse order) are used regularly in sales analysis.

2017-08-15 14:58 UTC, RoganW commented on superset/assets/javascripts/explore/stores/controls.jsx
> +      choices: (state.datasource) ? state.datasource.order_by_choices : [],
If I want to compare the options ordering by`metric descending` or `metric ascending`, I  would prefer to create a new slice specially to show that.

2017-08-16 18:29 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    multi: true,
but don't you run out of options then? each option can only be used once isn't it?

2017-08-16 18:31 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    multi: true,
oh I see, but what if you want two different filters to be sorted on the same metric?

2017-08-17 04:32 UTC, RoganW commented on superset/assets/javascripts/explore/stores/controls.jsx
> +    multi: true,
By default, filters will be sorted by metric in descending order, if not select any`filter_order ` related to them.

2018-04-23 05:36 UTC, mistercrunch commented
Notice: this issue has been closed because it has been inactive for 250 days. Feel free to comment and request for this issue to be reopened.

2018-04-23 05:36 UTC, closed without merging