Adding hook for external password store for databases
apache/superset pull request #3436
Opened 2017-09-08 19:23 UTC by fabianmenges

This allows you to write a plugin for an external password store for you sql passwords. 

My employer has a strict policy that all credentials are managed by a single system, this now allowing us to store SQL passwords inside of the Superset meta-database .

2017-09-08 22:15 UTC, xrmx commented on superset/config.py
> +# In order to hook up a custom password store for all SQLACHEMY connections
Better add documentation to documentation instead of config files. You can just set 
`SQLALCHEMY_CUSTOM_PASSWORD_STORE = False` here

2017-09-12 03:42 UTC, mistercrunch requested changes
Agreed with @xrmx , please add a note in `installation.rst` (and rebase)

2017-09-13 01:14 UTC, fabianmenges commented on tests/core_tests.py
> +        if conn_pre.password:
Sqlite does not support passwords, so this test would fail otherwise.

2017-09-14 03:58 UTC, mistercrunch approved these changes

2017-09-14 03:59 UTC, merged