Js controls
apache/superset pull request #4272
Opened 2018-01-23 22:13 UTC by hughhhh

Added JS controls to remaining DeckGL layers
merged small bugfix with arc layer payload #4238 

@mistercrunch

2018-01-23 22:34 UTC, mistercrunch requested changes
Running into a bit of a conflict with https://github.com/apache/incubator-superset/pull/4262 here. Let's make sure both PRs align.

2018-01-23 22:34 UTC, mistercrunch commented on superset/assets/visualizations/deckgl/layers/arc.jsx
> +    data = data.map(jsFnMutator);
With my recent PR we moved to `js_data_mutator` instead of `js_datapoint_mutator` and the call goes `data = jsFnMutator(data);`

2018-01-23 22:34 UTC, mistercrunch commented on superset/assets/visualizations/deckgl/layers/hex.jsx
> +  if (fd.js_datapoint_mutator) {
Same comment as above. Related PR: https://github.com/apache/incubator-superset/pull/4262

2018-01-23 22:34 UTC, mistercrunch commented on superset/assets/visualizations/deckgl/layers/screengrid.jsx
> +  if (fd.js_datapoint_mutator) {
Same here...

2018-01-23 22:46 UTC, hughhhh commented
@mistercrunch lets make sure #4262 goes in first

2018-01-24 16:13 UTC, mistercrunch approved these changes

2018-01-24 16:16 UTC, mistercrunch commented
Now that my changes are in `master` let's rebase to make sure things look ok. We may want to switch to avoid the "Squash and merge" flow in Github an follow the "Create a merge commit" option instead eventually.

2018-01-25 00:10 UTC, mistercrunch commented on superset/assets/javascripts/explore/stores/controls.jsx
> +  js_data_mutator: jsFunctionControl(
Sorry I had not yet merge this change when I asked you to rebase earlier, now it's merge and you should re-re-rebase

2018-01-25 22:07 UTC, merged