Add time grain blacklist and tests for validity
apache/superset pull request #5380
Opened 2018-07-12 11:43 UTC by villebro

- Refactor time grain logic to avoid the use of conflicting names and durations
- Harmonize discrepancies in time grains, e.g. P3M (Druid) vs P0.25Y (all others)
- Add TIME_GRAIN_BLACKLIST to config.py to be able to remove unwanted time grains, e.g. 5/10/15 mins
- Add tests for blacklist and validity of defined time grains

2018-07-12 14:20 UTC, mistercrunch commented
@betodealmeida

2018-07-18 14:04 UTC, villebro commented
Also added functionality to be able to add new custom time grains in `config.py` (`TIME_GRAIN_ADDONS` and `TIME_GRAIN_ADDON_FUNCTIONS`). This could be used to move some less used time grains out of db_engine_specs, while still allowing for end users to define their own custom time grains where needed.

Question: in `config.py`, which would be preferable: using a blacklist to remove predefined options (e.g. `VIZ_TYPE_BLACKLIST`), or effectively defining a whitelist (e.g. `LANGUAGES`)?

2018-07-23 11:06 UTC, villebro commented
Comments would be much appreciated @betodealmeida @mistercrunch . This PR would make it easier and to manage and add new time grains in production environments. If this PR is not aligned with future plans for Superset I will be happy make necessary changes or close the PR.

2018-07-23 19:49 UTC, betodealmeida requested changes
This looks great, @villebro! It greatly simplifies the definition of new durations and reduces a lot of the duplication.

I have just a few comments on the code, mostly nits, and there's one place where the function is wrong (probably due to an accidental deletion).

> Question: in config.py, which would be preferable: using a blacklist to remove predefined options (e.g. VIZ_TYPE_BLACKLIST), or effectively defining a whitelist (e.g. LANGUAGES)?

I think doing a blacklist works better here.

2018-07-24 05:29 UTC, villebro commented on superset/db_engine_specs.py
> +    'P1W/1970-01-03T00:00:00Z': 'week_ending_saturday',
Good idea, done.

2018-07-24 05:31 UTC, villebro commented on superset/db_engine_specs.py
> +    ret_list = list()
Thanks, will try to remember this in the future.

2018-07-24 05:32 UTC, villebro commented on superset/db_engine_specs.py
> +            name = time_grains.get(duration, None)
Good point.

2018-07-24 05:34 UTC, villebro commented on superset/db_engine_specs.py
> +    time_grain_functions = dict()
Fixed.

2018-07-24 05:42 UTC, villebro commented on superset/db_engine_specs.py
>  Grain = namedtuple('Grain', 'name label function duration')
Good point, I misremembered that `core.grains_dict()` created a dict that mapped `duration -> grain` and `name -> grain`, but the latter was in fact `label -> grain`. I've now removed name.

2018-07-24 05:43 UTC, villebro commented on superset/db_engine_specs.py
> +        return _create_time_grains_tuple(grains, grain_functions, blacklist)
Changed.

2018-07-24 05:45 UTC, villebro commented on superset/db_engine_specs.py
> +        'PT1S': "{col}) AT TIME ZONE 'UTC'",
Whoops, good catch!

2018-07-24 05:46 UTC, villebro commented on superset/db_engine_specs.py
> +        'PT5M': "DATEADD(MINUTE, FLOOR(DATE_PART(MINUTE, {col}) / 5) * 5, \
Yes; not sure if it's the most efficient way of doing it, but managed to get good performance on a semi-large dataset, so should be good to go.

2018-07-24 05:50 UTC, villebro commented on superset/db_engine_specs.py
> +    }
👍

2018-07-24 05:51 UTC, villebro reviewed
All proposed changes implemented.

2018-07-24 13:08 UTC, villebro commented
@betodealmeida I tried to remove `name` from Grain and updating `time_column_grains()` and `data()` in `connectors/sqla/models.py`, but got slightly overwhelmed by the frontend code. For instance, `controls.jsx` seems to have similar but slightly different grains, and am unsure where these definitions are used:

https://github.com/apache/incubator-superset/blob/bea0a0aa1590d073365ecf74d75a054643dbe3b7/superset/assets/src/explore/controls.jsx#L750-L776

I'm sure I will be able to sort out how the frontend logic works, but it will take time, so I propose merging this and removing `name` in a separate PR.

2018-07-24 18:30 UTC, betodealmeida approved these changes
Awesome! Thank you so much for doing this, @villebro!

2018-07-24 19:18 UTC, villebro commented
Great, thanks @betodealmeida !

2018-07-28 07:34 UTC, villebro commented
@betodealmeida FYI rebased to resolve conflict, any chance of getting this merged out of the way?

2018-07-30 16:32 UTC, betodealmeida commented
@mistercrunch, can you merge this? I still don't have merging privilege.

2018-07-31 06:44 UTC, merged