Sundry fixes
apache/superset pull request #6720
Opened 2019-01-18 05:18 UTC by agrawaldevesh

A bunch of unrelated fixes as I have tried to deploy Superset in my environment and paired it with Presto.

2019-01-22 16:58 UTC, mistercrunch requested changes
Minor comment, otherwise LGTM

2019-01-22 16:58 UTC, mistercrunch commented on superset/connectors/sqla/views.py
> +                'table name\n{}').format(table.name, traceback.format_exc()))
I wouldn't straight out display the stack trace to the user here.

2019-01-23 06:12 UTC, agrawaldevesh commented
@mistercrunch , diff is again ready for review as I have incorporated your requested changes.

2019-01-24 05:12 UTC, mistercrunch approved these changes

2019-01-24 05:12 UTC, merged