[Fix] Snowflake connection bug of Apache Superset
apache/superset pull request #9084
Opened 2020-02-04 14:05 UTC by saurabhperiwal

Fix #9083

### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Snowflakes connector was not working because snowflake-sqlalchemy was missing

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TEST PLAN

### ADDITIONAL INFORMATION

Fixes #9083 
- [ ] Has associated issue: #9083 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

2020-02-04 16:23 UTC, dpgaspar requested changes
snowflake is an optional dependency, take a look at: https://superset.incubator.apache.org/installation.html#database-dependencies

2020-02-04 16:26 UTC, villebro requested changes

2020-02-04 16:26 UTC, villebro commented on setup.py
> +	"snowflake-sqlalchemy>=1.2.0",
Please fix the indentation here and move to `extras_require`; `snowflake-sqlachemy` is not required to run Superset.

2020-02-04 16:26 UTC, villebro commented on requirements.txt
> +snowflake-sqlalchemy==1.2.0
`extra_requires` should not be included in `requirements.txt`. This change is also pulling in libraries that are not apache compatible, at least `requests` but perhaps others, too.

2020-03-09 21:35 UTC, closed without merging

2020-03-09 21:35 UTC, craig-rueda commented
Closing for now - this is pulling in too many external libs, which should be added into extras