[datasets] new, listview (react)
apache/superset pull request #9197
Opened 2020-02-25 02:27 UTC by nytai

### CATEGORY

Choose one

- [ ] Bug Fix
- [ ] Enhancement (new features, refinement)
- [x] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

dependent on #9129 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TEST PLAN

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

2020-03-10 21:34 UTC, villebro requested changes
Two type nits

2020-03-10 21:34 UTC, villebro commented on superset/connectors/sqla/models.py
> +    def changed_by_name(self):
can we add typing: `def changed_by_name(self) -> str:`

2020-03-10 21:34 UTC, villebro commented on superset/connectors/sqla/models.py
> +    def changed_by_url(self):
here, too: `def changed_by_url(self) -> str:`

2020-03-11 04:18 UTC, mistercrunch approved these changes

2020-03-11 19:34 UTC, villebro commented
When playing around with this, I get the following error with the following filters:
- SQL Lab view (checked)
- Database (empty)

![image](https://user-images.githubusercontent.com/33317356/76456467-b2fcf300-63df-11ea-9e71-8ea5eb953e16.png)

2020-03-11 23:24 UTC, nytai commented
@villebro Thanks for catching that, I also found that my implementation of the database filter was incorrect. Both issues have been addressed. I've also added an exception which should help catch incorrect filter config moving forward.

2020-03-12 01:52 UTC, suddjian commented on superset-frontend/src/views/datasetList/DatasetList.tsx
> +      endpoint: `/api/v1/dashboard/${id}`,
I think you want a different endpoint here

2020-03-12 05:26 UTC, villebro approved these changes
There seems to be some JS lint, otherwise LGTM. This is a *really* nice improvement to the user experience, great work! 👍

2020-03-12 19:17 UTC, nytai commented
I just realized this change will remove the create button for datasets(tables). For Charts and Dashboards there was the `NEW` button to fall back on, however that button is missing Tables. This is a blocker, I'll have to figure something out

2020-03-13 04:46 UTC, nytai commented
Added a `+` button 

<img width="1234" alt="Screen Shot 2020-03-12 at 6 35 10 PM" src="https://user-images.githubusercontent.com/10255196/76590619-f8d2bd80-64aa-11ea-919c-f44a91e28c0e.png">

2020-03-13 19:35 UTC, merged